### PR TITLE
Add code samples for Remote Config operations

### PR DESCRIPTION
**Pull request by lahirumaramba**
- Related to: firebase/firebase-admin-java#476

- Samples to appear on https://firebase.google.com/docs/remote-config/automate-rc and https://firebase.google.com/docs/remote-config/templates

### CODE REVIEW

**Comment by samtstern** [comment]
@lahirumaramba LGTM, I assume the CI failures are because the SDK has not released yet?  Please wait until CI is green to merge these.

**Review by kroikie — APPROVED** [review]
LGTM

**Comment by lahirumaramba** [comment]
> @lahirumaramba LGTM, I assume the CI failures are because the SDK has not released yet? Please wait until CI is green to merge these.

@samtstern Thanks! Yes, the current SDK the project is pointing to does not have the new RC features, hence the CI failures. Once the SDK is released, do you think I should update `admin/build.gradle` as well? If so, I could include that change in the same PR.

**Comment by samtstern** [comment]
@lahirumaramba yep exactly, if you bump the dependency in this PR as well then it will be green before you merge.

If these snippets have to appear in docs via `includecode` then you can have the Tech Writer use `git_revision="lm-rc-snippets"` to stage from your branch and then make a note to remove that after launch.

**Comment by egilmorez** [comment]
Sam's right about git_revision, but it comes with a caveat: you can't use the newer, registry-based named snippets with that flag.  So I'd resist that unless there's a big rush.

**Comment by samtstern** [comment]
@egilmorez actually `git_revision` is totally compatible with the Snippet Registry and there's even a refactoring workflow to undo it!
https://g3doc.corp.google.com/devrel/tools/includecode/g3doc/guide-refactor-snippets.md?cl=head#option-2-migrate-branches

**Comment by egilmorez** [comment]
Check you guys out!  I'll try that today; I'm an excellent test for ease-of-use criteria :D

**Comment by lahirumaramba** [comment]
@samtstern @hiranya911 :
Updated `admin/build.gradle` to point to the latest `firebase-admin v7.1.0`. Had to update `Notification` to use the `builder()` in `FirebaseMessagingSnippets`. Let me know if you would rather have us done that in a separate PR (the upgrade and changes to `FirebaseMessagingSnippets`) and then follow up with this PR.
Thank you!

**Review by samtstern — APPROVED** [review]

**Pull request merged**
